[package]
name = "sentinel0-hub-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
sentinel0-proto.workspace = true

[lints]
workspace = true
